SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ENEMY_MIN_RADIUS = 20
ENEMY_KINDS = 3
ENEMY_SPAWN_RATE = 0.8  # seconds
ENEMY_MAX_RADIUS = ENEMY_MIN_RADIUS * ENEMY_KINDS

PLAYER_RADIUS = 20

PLAYER_TURN_SPEED = 300
PLAYER_SPEED =  200

SHOT_RADIUS = 5
PLAYER_SHOOT_SPEED = 500

PLAYER_SHOOT_COOLDOWN = 0.3
